### ISSUE TITLE
Cardinal client addon hangs on mojang loading screen with certain mods

### ISSUE THREAD

**Issue by Echo-noen** [sisby-folk/switchy#85]
Launching the game with MInecraft 1.21 and Fabric Loader 0.15.11 with the [Comforts](https://modrinth.com/mod/comforts) and/or [Trinikets](https://modrinth.com/mod/trinkets) mods impedes the game from loading past the Mojang screen

**Comment by MinecraftMoments** [comment]
i think this happens without comforts/trinkets, i was having this issue too and i didn't have comforts or trinkets on (noting even tho i don't know what other mod(s) might have also affected this and i am too busy with other things to check right now)

**Comment by twuggle** [comment]
I can confirm this issue also occurs on Fabric Loader 0.16.7 and is triggered by Trinkets exclusively within my own mod load; the Minecraft application attempts to "load twice" on the Mojang screen, but the ability to functionally play the game remains (UI buttons work, I accidentally navigated to a donate page through Mod Menu)

**Comment by infinitephantasm** [comment]
after doing some testing after noticing this issue on my own little modpack, it seems that the Show Me Your Skin! mod happens to cause this issue consistently on every single start, and immediately ceases when it's disabled/removed.

when it happens, this error appears in logs, likely explaining the loading screen locking up (as it appears to immediately reload resourcepacks and then never finishes properly):
```
[01:48:33] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: arcpocalypse:suspicious_broom
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at knot/net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:121) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.7.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: arcpocalypse:suspicious_broom
	at knot/com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
	at knot/com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar:?]
	at knot/folk.sisby.switchy.client.CardinalClientModuleLoader.lambda$apply$2(CardinalClientModuleLoader.java:90) ~[switchy-cardinal-ui-2.9.4+1.21-bb0007887d07352c.jar:?]
	at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
	at knot/folk.sisby.switchy.client.CardinalClientModuleLoader.apply(CardinalClientModuleLoader.java:62) ~[switchy-cardinal-ui-2.9.4+1.21-bb0007887d07352c.jar:?]
	at knot/folk.sisby.switchy.client.CardinalClientModuleLoader.method_18788(CardinalClientModuleLoader.java:43) ~[switchy-cardinal-ui-2.9.4+1.21-bb0007887d07352c.jar:?]
	at knot/net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 15 more
```
this doesn't happen when its library mod CICADA is loaded, so assumingly Show Me Your Skin! is the mod that is at fault for the conflict/incompatibility

here's the logs for a [successful start](https://github.com/user-attachments/files/17538452/latest.log) and a [failed start](https://github.com/user-attachments/files/17538454/2024-10-28-1.log), if it helps

**Comment by Wolfystarrs** [comment]
I've found the same issue on 1.21.1 fabric loader 0.16.9 with mods Origins, Polymorph and SIHYWTCAMD

**Comment by sisby-folk** [comment]
This is affecting me personally so now i _gotta_ fix it today

**Comment by sisby-folk** [comment]
fixed in latest
